<a href="https://colab.research.google.com/github/zulfanandria/Deep-Learning-Prerequisites/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Arrays vs Lists

In [ ]:
import numpy as np

In [ ]:
L = [1,2,3]

In [ ]:
A = np.array([1,2,3])

In [ ]:
for e in L:
  print(e)

1
2
3


In [ ]:
for e in A:
  print(e)

1
2
3


In [ ]:
L.append(4)

In [ ]:
L

[1, 2, 3, 4]

In [ ]:
A.append(4)

AttributeError: ignored

In [ ]:
L + [5]

[1, 2, 3, 4, 5]

In [ ]:
A + np.array([4])

array([5, 6, 7])

In [ ]:
A + np.array([4,5,6])

array([5, 7, 9])

In [ ]:
A + np.array([4,5])

ValueError: ignored

In [ ]:
2 * A

array([2, 4, 6])

In [ ]:
2 * L

[1, 2, 3, 4, 1, 2, 3, 4]

In [ ]:
L + L

[1, 2, 3, 4, 1, 2, 3, 4]

In [ ]:
L2 = []
for e in L:
  L2.append(e+3)

In [ ]:
L2

[4, 5, 6, 7]

In [ ]:
L2 = [e + 3 for e in L]
L2

[4, 5, 6, 7]

In [ ]:
L**2

TypeError: ignored

In [ ]:
L2 = []
for e in L:
  L2.append(e**2)

In [ ]:
L2

[1, 4, 9, 16]

In [ ]:
A**2

array([1, 4, 9])

In [ ]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [ ]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [ ]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [ ]:
np.tanh(A)

array([0.76159416, 0.96402758, 0.99505475])

# The Dot Product

In [ ]:
a = np.array([1,2])
b = np.array([3,4])

In [ ]:
dot = 0
for e, f in zip(a,b):
  dot += e*f
dot

11

In [ ]:
dot = 0
for i in range(len(a)):
  dot += a[i] * b[i]
dot

11

In [ ]:
a * b

array([3, 8])

In [ ]:
np.sum(a * b)

11

In [ ]:
(a * b).sum()

11

In [ ]:
np.dot(a,b)

11

In [ ]:
a.dot(b)

11

In [ ]:
a@b

11

In [ ]:
amag = np.sqrt((a*a).sum())

In [ ]:
amag

2.23606797749979

In [ ]:
np.linalg.norm(a)

2.23606797749979

In [ ]:
cosangle = a.dot(b) / (np.linalg.norm(a)*np.linalg.norm(b))

In [ ]:
cosangle

0.9838699100999074

In [ ]:
angle = np.arccos(cosangle)
angle

0.17985349979247847

# Matrices

In [ ]:
L = [[1,2],[3,4]]
L

[[1, 2], [3, 4]]

In [ ]:
L[0]

[1, 2]

In [ ]:
L[0][1]

2

In [ ]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [ ]:
A[0][1]

2

In [ ]:
A[0,1]

2

In [ ]:
A[:,0]

array([1, 3])

In [ ]:
A.T

array([[1, 3],
       [2, 4]])

In [ ]:
np.exp(A)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [ ]:
np.exp(L)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [ ]:
B = np.array([[1,2,3],[4,5,6]])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
A.dot(B)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [ ]:
A.dot(B.T)

ValueError: ignored

In [ ]:
np.linalg.det(A)

-2.0000000000000004

In [ ]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
np.linalg.inv(A).dot(A)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [ ]:
np.trace(A)

5

In [ ]:
np.diag(A)

array([1, 4])

In [ ]:
np.diag([1,4])

array([[1, 0],
       [0, 4]])

In [ ]:
np.linalg.eig(A)

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [ ]:
Lam, V = np.linalg.eig(A)

In [ ]:
V[:, 0] * Lam[0] == A @ V[:,0]

array([ True, False])

In [ ]:
V[:, 0] * Lam[0], A @ V[:,0]

(array([ 0.30697009, -0.21062466]), array([ 0.30697009, -0.21062466]))

In [ ]:
np.allclose(V[:,0] * Lam[0], A @ V)

False

# Solving Linear Systems

In [ ]:
A = np.array([[1,1],[1.5,4]])
B = np.array([2200, 5050])

In [ ]:
np.linalg.solve(A, B)

array([1500.,  700.])

In [ ]:
np.linalg.inv(A).dot(B)

array([1500.,  700.])

# Generating Data

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
10 * np.ones((2,3))

array([[10., 10., 10.],
       [10., 10., 10.]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.random.random()

0.8351901985817398

In [ ]:
np.random.random((2,3))

array([[0.21782201, 0.85461925, 0.71256514],
       [0.42296623, 0.08729327, 0.34785223]])

In [ ]:
np.random.randn(2,3)

array([[ 0.45671118, -0.15137517,  0.97022663],
       [ 0.09757943,  0.7283097 , -1.0501553 ]])

In [ ]:
R = np.random.randn(10000)

In [ ]:
R.mean()

0.0031901102271555785

In [ ]:
np.mean(R)

0.0031901102271555785

In [ ]:
R.var()

1.012344059267184

In [ ]:
R.std()

1.0061530993179835

In [ ]:
R = np.random.randn(10000,3)

In [ ]:
R.mean(axis=0)

array([ 0.00619081,  0.01205411, -0.00637248])

In [ ]:
R.mean(axis=1)

array([-0.75048098,  0.60861225, -1.12950952, ...,  0.1479388 ,
        0.591263  ,  0.21773561])

In [ ]:
R.mean(axis=1).shape

(10000,)

In [ ]:
np.cov(R)

array([[ 0.17236998, -0.33677207,  0.44010124, ...,  0.1270657 ,
        -0.1585064 , -0.69198392],
       [-0.33677207,  0.85649873, -0.84533206, ...,  0.63435893,
        -0.35697959,  0.85061386],
       [ 0.44010124, -0.84533206,  1.12474524, ...,  0.38901258,
        -0.45348625, -1.80348478],
       ...,
       [ 0.1270657 ,  0.63435893,  0.38901258, ...,  4.017727  ,
        -3.08079812, -2.73915315],
       [-0.1585064 , -0.35697959, -0.45348625, ..., -3.08079812,
         2.38451485,  2.31998857],
       [-0.69198392,  0.85061386, -1.80348478, ..., -2.73915315,
         2.31998857,  4.04418715]])

In [ ]:
np.cov(R).shape

(10000, 10000)

In [ ]:
np.cov(R.T)

array([[ 0.97672526, -0.00529163,  0.01175892],
       [-0.00529163,  1.01591246,  0.01041451],
       [ 0.01175892,  0.01041451,  1.01886539]])

In [ ]:
np.cov(R, rowvar=False)

array([[ 0.97672526, -0.00529163,  0.01175892],
       [-0.00529163,  1.01591246,  0.01041451],
       [ 0.01175892,  0.01041451,  1.01886539]])

In [ ]:
np.random.choice(10, size=(3, 3))

array([[1, 2, 2],
       [6, 5, 3],
       [0, 8, 5]])